name: 'Cancel Workflow Action'
description: 'This Action will cancel any previous runs that are not `completed` for a given workflow.'
author: styfle
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  workflow_id:
    description: 'Optional - A single Workflow ID or a comma separated list of IDs'
    required: false
  ignore_sha:
    description: 'Optional - Allow canceling other workflows with the same SHA. Useful for the `pull_request.closed` event.'
    required: false
    default: 'false'
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: ${{ github.token }}
    required: false
  all_but_latest:
    description: "Cancel all actions but the last one"
    required: false
    default: 'false'
  ignore_branches_on_push:
    description: "Do not trigger cancellation for given branches when trigger event is push"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
