name: 'Cancel Workflow Action'
description: 'This Action will cancel any previous runs that are not `completed` for a given workflow.'
author: styfle
branding:
  icon: 'stop-circle'  
  color: 'white'
inputs:
  workflow_id:
    description: 'Optional - A single Workflow ID or a comma separated list of IDs (if ommitted, current workflow is used)'
    required: false
  access_token:
    description: 'Your GitHub Access Token, ie: {{ github.token }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
