name: Cancel All Workflows
on: push

# Push again in the same branch
# automatically all the worklows will be cancelled
# To prevent this cancellation, comment this workflow
jobs:
  task:
    runs-on: ubuntu-latest
    name: Task
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Step
        uses: ./ # Uses an action in the root directory
        with:
          access_token: ${{ github.token }}
          workflow_id: all
      - uses: actions/setup-node@v3.6.0
      - run: echo 'Sleeping...'; sleep 120; echo 'Done.';
